### ISSUE TITLE
error using the `--email` option

### ISSUE THREAD

**Issue by bornlikeariver** [sampzzz/blackbird#76]
```
Traceback (most recent call last):
  File "G:\000\blackbird\blackbird.py", line 215, in <module>
    verifyEmail(config.currentEmail)
  File "G:\000\blackbird\src\modules\core\email.py", line 125, in verifyEmail
    foundAccounts = list(filter(filterFoundAccounts, results["results"]))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\000\blackbird\src\modules\utils\filter.py", line 7, in filterFoundAccounts
    if site["status"] == "FOUND":
       ~~~~^^^^^^^^^^
TypeError: 'TypeError' object is not subscriptable
```
this is the main error that i get when trying to use the `--email` parameter.
in `./src/modules/utils/filter.py` i added a `print(site)` before `if site["status"] === "FOUND":` and here is the log:

```
{'name': 'Gravatar', 'url': 'https://gravatar.com/0925f997eb0d742678f66d2da134d15d842d57722af5f7605c4785cb5358831b.json', 'status': 'NOT-FOUND', 'metadata': []}
{'name': 'Adobe', 'url': 'https://auth.services.adobe.com/signin/v2/users/accounts', 'status': 'FOUND', 'metadata': [[]]}
{'name': 'Duolingo', 'url': 'https://www.duolingo.com/2017-06-30/users?email=user@email.com', 'status': 'FOUND', 'metadata': []}
{'name': 'Chess.com', 'url': 'https://www.chess.com/callback/email/available?email=user@email.com', 'status': 'FOUND', 'metadata': []}
{'name': 'Notion', 'url': 'https://www.notion.so/api/v3/getLoginOptions', 'status': 'FOUND', 'metadata': []}
{'name': 'Spotify', 'url': 'https://spclient.wg.spotify.com/signup/public/v1/account?validate=1&email=user@email.com', 'status': 'FOUND', 'metadata': []}
{'name': 'Strava', 'url': 'https://www.strava.com/athletes/email_unique?email=user@email.com', 'status': 'NOT-FOUND', 'metadata': []}
{'name': 'Twitter', 'url': 'https://api.twitter.com/i/users/email_available.json?email=user@email.com', 'status': 'NOT-FOUND', 'metadata': []}
{'name': 'NetShoes', 'url': 'https://www.netshoes.com.br/auth/account/exists/user@email.com', 'status': 'NOT-FOUND', 'metadata': []}
{'name': 'OLX', 'url': 'https://apigw.olx.com.br/v0/user/login/check_email', 'status': 'NOT-FOUND', 'metadata': []}
{'name': 'Milanuncios', 'url': 'https://userprofiles.gw.milanuncios.com/api/v2/users', 'status': 'NOT-FOUND', 'metadata': []}
{'name': 'El Mundo', 'url': 'https://seguro.elmundo.es/ueregistro/v2/usuarios/registro', 'status': 'NOT-FOUND', 'metadata': []}
{'name': 'Xvideos', 'url': 'https://www.xvideos.com/account/checkemail?email=user@email.com', 'status': 'FOUND', 'metadata': []}
{'name': 'Picsart', 'url': 'https://api.picsart.com/users/email/existence?email_encoded=0&emails=user@email.com', 'status': 'FOUND', 'metadata': []}
replace() argument 2 must be str, not None
Traceback (most recent call last):
[...]
```

i'm not *too* experienced with this kind of stuff, but i'm assuming the fact that there is a `replace()` statement which has a second argument that passes as `None`, instead of a string could be the issue here.

if you could give some guidance here, that would be incredibly helpful.
thanks.

sys info:
* os: windows 11
* python ver: Python 3.11.3

**Comment by p1ngul1n0** [comment]
Hi @bornlikeariver,

Thanks for the report. Can you please send me the .log file to aid in debugging?

This happened in all your executions or only in a specfic one ?

**Comment by p1ngul1n0** [comment]
I just updated the main branch with a fix, update and test please.
